config/routes.rb
Rails.application.routes.draw do

  
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  
  get 'signup' => 'users#new'

  
  get 'ideas' => 'static_pages#ideas'

  get 'subscribe' => 'subscriptions#index'
  post 'subscribe' => 'subscriptions#create'
  delete 'usubscribe' => 'subscriptions#destroy'
  
  get 'newspaper' => 'newspaper#index'
  
  get 'feeds' => 'feeds#index'
  get 'add' => 'feeds#new'
  get 'fetch' => 'feeds#fetch'
  post 'add' => 'feeds#create'
  
  
  delete 'logout' => 'sessions#destroy'

  get 'entries' => 'entries#index'
  get 'websites' => 'websites#index'
  put 'websites' => 'websites#update'
  resources :websites, only: [:index, :update]

  resources :entries
  resources :subscriptions
  resources :users
  resources :feeds
  resources :entries
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  validates :url, presence: true
  validates_format_of :url, :with => URI::regexp(%w(http https))
  #  has_many :entries, through: :sources
  # has_many :sources, dependent: :destroy
  #  has_many :subscriptions, dependent: :destroy
  #  has_many :users, through: :subscriptions

  def subscribed_by?(user)
    Subscription.exists?(feed_id: self.id, user_id: user.id)
  end


#  def compatible
#  update_attribute(:compatible, "true")
#  end

#  def incompatible
#    update_attribute(:compatible, "false")
#  end
  
  
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  before_action :admin_user, only: [:edit, :update, :fetch]
  before_action :logged_in_user, only: [:index, :new, :create]
  
  def index
    @feeds = Feed.paginate(page: params[:page], :per_page => 9)
  end
  
  def new
    @feed = Feed.new
  end

  def create
    # να παίρνει το τίτλο από την πηγή
    # @feed = Feed.new(feed_params)
    # if @feed.save
    #  flash[:info] = "Η ροή καταχωρήθηκε με επιτυχία."
    #  redirect_to feeds_path
    #else
    #  render 'new'
    #end
  end

  def edit
    @feed = Feed.find(params[:id])
  end

  #
  def update
    @feed = Feed.find(params[:id])
    if @feed.update_attributes(feed_params)
      flash[:success] = "η Αλλαγή έχει γίνει με επιτυχία"
      redirect_to subscriptions_path
    else
      render 'edit'
      #@feed = Feed.new(feed_params)
      #if @feed.save
      #  flash[:info] = "Η ροή καταχωρήθηκε με επιτυχία."
      #redirect_to feeds_path
      #else
      # render 'new'
    end
  end

  def destroy
    #  Feed.find(params[:id]).destroy
    #  flash[:success] = "Ο ροή διαγράφηκε"
    #  redirect_to feeds_url
    # Κανονικά η πιο κάτω ενέργεια είναι δουλειά του subscriptions_controller
    # Έχει μπει εδώ γιατί υπήρχε πρόβλημα στην υλοποίηση 
    Subscription.where(user_id: current_user.id,feed_id: params[:id].to_i).destroy_all
    redirect_to subscriptions_path
    flash[:success] = "Η ροή #{Feed.find(params[:id].to_i).title} έχει διαγραφεί από τις συνδρομές σας"
  end

  # Τραβά τα άρθρα από τη πηγή και τα καταχωρεί στη βάση
  # 
  # @param: Feed.id
  #
  #
  def fetch
    feed = Feed.find(params[:id])
    FetchFeed.new(feed).fetch
    flash[:success] = " άρθρα έχουν προστεθεί"
    redirect_to feeds_path(:page => params[:page])
  end
  
  
  
  private

  def feed_params
    params.require(:feed).permit(:title, :url, :compatible)
  end

end

app/helpers/feeds_helper.rb
module FeedsHelper

end

app/views/feeds/_feed.html.erb
<li>
  <!-- Αυτή η όψη εκφράζει subscription - Να μετακινηθεί με τη πρώτη ευκαιρία -->
  <% if feed.subscribed_by?(current_user) %>
  <%= link_to "Διαγραφή", feed, method: :delete %>
  <% else %>
  <%= link_to "Εγγραφή",  edit_subscription_url(feed.id) %>
  <% end %>
  <!-- {controller: "subscriptions", action: "create", url: feed.url} -->
  <!--% else %-->
  <!--% end %-->
  | <%= link_to feed.title, feed.url %>
  <!--%= link_to "Ανανέωση", edit_fetch_items_from_feed_url(feed.id) %-->
  <!--% if feed.subscribed_by?(current_user)%-->
  <!--%= link_to "Διαγραφή", feed, method: :delete %-->
</li>

app/views/feeds/_form.html.erb
<!-- it's better to rename that file because - different from other forms -->
<%= form_for(@feed) do |f| %>
<%= render 'shared/error_feeds'%>
<div class="field">
  <%= f.label :url %><br>
  <%= f.text_field :url %>
</div>
<div class="actions">
  <%= f.submit "Προσθήκη", class: "btn btn-primary"%>
</div>
<% end %>

app/views/feeds/edit.html.erb
<% provide(:title, "Επεξεργασία Ροής") %>
<h1>Ανανέωση πληροφοριών ροής</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@feed) do |f| %>
    <%= render 'shared/error_feeds' %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
    <%= f.submit "Αποθήκευση", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/feeds/index.html.erb
<% provide(:title, 'Όλες οι πηγές') %>
<h1>Όλες οι πηγές</h1>
<%= will_paginate%>
<% @feeds.each do |feed| %>
<li>
  <!-- comments -->
  <!-- Αυτή η όψη εκφράζει subscription - Να μετακινηθεί με τη πρώτη ευκαιρία -->

  <%= link_to feed.title, feed.url %>
  
  <% if !current_user.admin? %>
  <% if feed.subscribed_by?(current_user) %>
  <%= link_to "Διαγραφή", feed, method: :delete %>
  <% else %>
  <%= link_to "Εγγραφή",  edit_subscription_url(feed.id) %>
  <% end %>
  <% else %>
  | <%= link_to "Επεξεργασία",   edit_feed_path(feed.id) %> |
  <%= link_to "Ανανέωση", fetch_path(:id => feed.id, :page => params[:page] ) %>
  <% end %>

  <% end %>
  
</li>

app/views/feeds/new.html.erb
<% provide(:title, "Νέα ροή") %>
<h1><%= yield(:title)%></h1>

<%= render 'form'%>

app/views/feeds/update.html.erb
hello