config/routes.rb
Rails.application.routes.draw do

  
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  
  get 'signup' => 'users#new'

  
  get 'ideas' => 'static_pages#ideas'

  get 'subscribe' => 'subscriptions#index'
  post 'subscribe' => 'subscriptions#create'
  delete 'usubscribe' => 'subscriptions#destroy'
  
  get 'newspaper' => 'newspaper#index'
  
  get 'feeds' => 'feeds#index'
  get 'add' => 'feeds#new'
  get 'fetch' => 'feeds#fetch'
  post 'add' => 'feeds#create'
  
  
  delete 'logout' => 'sessions#destroy'

  get 'entries' => 'entries#index'
  get 'websites' => 'websites#index'
  put 'websites' => 'websites#update'
  resources :websites, only: [:index, :update]

  resources :entries
  resources :subscriptions
  resources :users
  resources :feeds
  resources :entries
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  
  def new
  end
  
  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Αποστάληκε η-μήνυμα με οδηγίες για επαναφορά κωδικού"
      redirect_to root_url
    else
      flash.now[:danger] = "Η ηλεκτρονική διεύθυνση δεν βρέθηκε"
      render 'new'
    end
  end

  def edit
  end

  private

  def get_user
    @user = User.find_by(email: params[:email])
  end

  # Confirms a valid user.
  def valid_user
    unless (@user && @user.activated? &&
            @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end

  # Checks expiration of reset token
  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Η επαναφορά κωδικού έχει λήξει."
      redirect_to new_password_reset_url
    end
  end
  
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Επαναφορά Κωδικού' %>
<h1>Επαναφορά Κωδικού'</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url:password_reset_path(params[:id])) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= hidden_field_tag :email, @user.email %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Εξίασα το κωδικό")%>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
    <%= f.label :email, "Ηλεκτρονική Διεύθυνση" %>
    <%= f.email_field :email, class: 'form-control' %>
    <%= f.submit "Επαναφορά", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>