config/routes.rb
Rails.application.routes.draw do

  
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  
  get 'signup' => 'users#new'

  
  get 'ideas' => 'static_pages#ideas'

  get 'subscribe' => 'subscriptions#index'
  post 'subscribe' => 'subscriptions#create'
  delete 'usubscribe' => 'subscriptions#destroy'
  
  get 'newspaper' => 'newspaper#index'
  
  get 'feeds' => 'feeds#index'
  get 'add' => 'feeds#new'
  get 'fetch' => 'feeds#fetch'
  post 'add' => 'feeds#create'
  
  
  delete 'logout' => 'sessions#destroy'

  get 'entries' => 'entries#index'
  get 'websites' => 'websites#index'
  put 'websites' => 'websites#update'
  resources :websites, only: [:index, :update]

  resources :entries
  resources :subscriptions
  resources :users
  resources :feeds
  resources :entries
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :concept
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :new, :edit, :destroy]
  include SubscriptionsHelper
  
  def index
    # Να αλλάξει
    # @subscriptions = Subscription.paginate(page: params[:page])
    # @feed = Feed.new
    # @subscription = Subscription.new
    @feeds = Feed.paginate(page: params[:page])
  end
  
  def show
    @subscription = Subscription.find(params[:user_id])
  end
  
  def new
    @feed = Feed.new
  end
  
  def create
    if uri?(params[:subscription][:url])
      # Αν δεν υπάρχει η ροή στη βάση να τη δημιουργεί
      # Κανονικά πρέπει να πάει στο create feed για να εφαρμόζεται το validate
      feed = Feed.find_or_initialize_by(url: params[:subscription][:url])
      if feed.new_record?
        # δαμέ αρκεί - αφού κάμει τη δουλειά μπορεί να τα φυλάει και για μετά
        xml = Feedjira::Feed.fetch_and_parse params[:subscription][:url] 
        feed.title = xml.title 
        feed.save
      end
      Subscription.find_or_create_by(user_id: current_user.id, feed_id: feed.id )    
      redirect_to subscriptions_path
      # flash message
      flash[:success] = "Έχεις εγγραφεί στη ροή"
    else
      redirect_to subscriptions_path
      # flash message
      flash[:success] = "Τι εν τούτο που μου δωκες"
    end
      
  end

  def edit
    # Το πιο κάτω κάνει δουλειά του create - να μετακινηθεί σε μια φάση
    Subscription.find_or_create_by(user_id: current_user.id, feed_id: params[:id] )
    redirect_to subscriptions_path
    # flash
    flash[:success] = "Έχεις εγγραφεί στη ροή"
  end

  def destroy

  end
  
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  # προσωρινή λύση - κανονικά πρέπει να ελέγχεται από το model του feed
  # δεν δουλεύει καλά - θα πρέπει να ελέγχει αν επιστρέφει κάτι το συγκεκριμένο url
  # και αν αυτό το κάτι είναι xml - παραδειγμα στα λανθασμένα δέχεται το http://www
  def uri?(string)
    uri = URI.parse(string)
    %w( http https ).include?(uri.scheme)
  rescue URI::BadURIError
    false
  rescue URI::InvalidURIError
    false
  end
  
end

app/views/subscriptions/_form.html.erb
<%= form_for(:subscription, url: subscriptions_path) do |f| %>

<div class="field">
  <%= f.label :url, "Υπερσύνδεσμος (RSS Feed link)" %><br>
  <%= f.text_field :url, class: 'form-control' %>
</div>

<div class="actions">
  <%= f.submit "Εγγραφή", class: "btn btn-primary"%>
</div>

<% end %>

app/views/subscriptions/create.html.erb
<%= form_for(:subscription, url: subscribe_path) do |f| %>

<div class="field">
  <%= f.label :url %><br>
  <%= f.text_field :url, class: 'form-control' %>
</div>

<div class="actions">
  <%= f.submit "Εγγραφή", class: "btn btn-primary"%>
</div>

<% end %>

app/views/subscriptions/destroy.html.erb
<h1>Subscriptions#destroy</h1>
<p>Find me in app/views/subscriptions/destroy.html.erb</p>

app/views/subscriptions/index.html.erb
<% provide(:title, 'Συνδρομές') %>
<h2>Καινούρια Συνδρομή</h2>

<%= render 'form'%>

<!--% current_user.my_subscriptions.each do |feed| %-->

<!--% current_user.other_subscriptions.each do |feed| %-->
<h2>Συνδρομές </h2>
<!--%= will_paginate%-->
<% @feeds.each do |feed| %>
<li>
  <%= link_to feed.title, feed.url %>
  |
  <% if feed.subscribed_by?(current_user) %>
  <%= link_to "Διαγραφή", feed, method: :delete %>
  <% else %>
  <%= link_to "Εγγραφή",  edit_subscription_url(feed.id) %>
  <% end %> 
  <% end %>
</li>

app/views/subscriptions/show.html.erb
<h1>Subscribe#show</h1>
<p>Find me in app/views/subscribe/show.html.erb</p>