config/routes.rb
Rails.application.routes.draw do

  
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  
  get 'signup' => 'users#new'

  
  get 'ideas' => 'static_pages#ideas'

  get 'subscribe' => 'subscriptions#index'
  post 'subscribe' => 'subscriptions#create'
  delete 'usubscribe' => 'subscriptions#destroy'
  
  get 'newspaper' => 'newspaper#index'
  
  get 'feeds' => 'feeds#index'
  get 'add' => 'feeds#new'
  get 'fetch' => 'feeds#fetch'
  post 'add' => 'feeds#create'
  
  
  delete 'logout' => 'sessions#destroy'

  get 'entries' => 'entries#index'
  get 'websites' => 'websites#index'
  put 'websites' => 'websites#update'
  resources :websites, only: [:index, :update]

  resources :entries
  resources :subscriptions
  resources :users
  resources :feeds
  resources :entries
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Ο κώδικας είναι διαθέσιμος στο <%= link_to "github", "https://github.com/Savinos90/sociopub", :target => "_blank" %>
    Εφαρμογή  sociopub  - <a href="http://www.cs.ucy.ac.cy/~salexa03/">Savvas Alexandrou</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Σχετικά", 'about' %></li>
      <li> <%= link_to "Επικοινωνία", contact_path %> </li> 
      <li><%= link_to "Νέα", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <%= link_to image_tag("sociopub.png", alt: "Sociopub logo", :height => "40%"), newspaper_path, id: "logo"%>
      <ul class="nav navbar-nav navbar-right">
	
	<% if !logged_in? %>
	
	<li><%= link_to "Αρχική", '/' %></li>
	
	<% else %>
	
	<% if current_user.admin? %>
	
	<li><%= link_to "Ιστοσελίδες", websites_path %></li>
	<li><%= link_to "Πηγές", feeds_path %></li>
	<li><%= link_to "Άρθρα", entries_path %></li>
	<li><%= link_to "Χρήστες", users_path %></li>
	
	<% else %>
	
	<li><%= link_to "Εφημερίδα", newspaper_path %></li>
	<li><%= link_to "Συνδρομές", subscriptions_path %></li>
	
	<% end %>
	
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	    Κουτί Ιδεών<b class="caret"> </b></a>
	  <ul class="dropdown-menu">
	    <li> <%= link_to "Τι εννοείς;", ideas_path %></li>
	    <li> <%= link_to "Στείλε tweet", "https://twitter.com/intent/tweet?text=@sociopub σου προτείνω %23feature <σύντομη περιγραφή>. <Δες την εικόνα που ανεβάζω για να καταλάβεις τι εννοώ>", :target => "_blank" %></li>
	    <li> <%= link_to "Στείλε email", ideas_path %></li>
	    <li> <%= link_to "Δες τι υλοποιείται ",  "https://github.com/Savinos90/sociopub/labels/current", :target => "_blank" %></li>
	    <li><%= link_to "Δες τι υλοποιήθηκε και τι εκκρεμεί!", "http://savinos90.github.io/sociopub-features/", :target => "_blank" %></li>
	  </ul>
	  
	  <% end %>
	<% if logged_in? %>
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	    Λογαριασμός<b class="caret"> </b>
	  </a>
	  <ul class="dropdown-menu">
	    <li><%= link_to "Προφίλ", current_user%></li>
	    <li><%= link_to "Ρυθμίσεις", edit_user_path(current_user) %></li>
	    <li class="divider"></li>
	    <li>
	      <%= link_to "Έξοδος", logout_path, method: "delete" %>
	    </li>
	  </ul>
	</li>
	<% else %>
	<li><%= link_to "Είσοδος", 'login' %></li>
	<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim'%>

  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message | %>
      <div class="alert alert-<%= message_type%>"><%= message %></div>
      
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
      <% debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>